server:
  port: 7788 #服务端口

spring:
  application:
    name: microservice-config-server  #指定服务名
  cloud:
    config:
      server:
        git:  #配置git仓库地址
          uri: https://github.com/xqqlove/myspconfig.git
          search-paths:
          username: xqqlove
          password: 201521040408xq,.
        default-label: master #分支名称